# Generated by Django 5.2.6 on 2025-11-30 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_aquisicao', models.DateField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacao_anual_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255)),
                ('manutencao_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('liquidado', 'Liquidado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_aquisicao', '-id'),
                'indexes': [models.Index(fields=['owner', 'data_aquisicao'], name='patr_owner_data_idx')],
            },
        ),
    ]
