# Versão do Docker Compose
version: '3.8'

# Definição dos serviços (contêineres)
services:

  # Serviço do Backend (Django)
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Serviço do Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    # --- A MELHOR PRÁTICA APLICADA ---
    # A diretiva 'env_file' instrui o Docker Compose a carregar as variáveis
    # de ambiente diretamente do arquivo .env.local em tempo de execução.
    # Isso mantém a configuração desacoplada da definição do serviço.
    env_file:
      - ./frontend/.env.local